version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=db_rides
      - PORT=8080
    env_file:
      - .env  # Adiciona essa linha para que o Docker leia o .env da raiz
    depends_on:
      - db
    
  db:
    image: mysql:8
    container_name: db_rides
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_rides
    ports:
      - "3306:3306"
      
    volumes:
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://backend:8080/api
    depends_on:
      - backend
